services:
  # A Docker web service
  - type: web
    name: clonekoyeb
    env: python
    startCommand: python3 main.py
    buildCommand: pip install -r requirements.txt
    repo:  https://github.com/madtoazenzio/clonekoyeb.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: master # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /

#End of yaml
